/**
 * Karmaraj Comprehensive Demo Universe Dataset
 * Showcases deep progression for instant showcase, demonstrations, and new player previews.
 */

export const DEMO_USER_PROFILE = {
  id: "demo-user-siddha",
  username: "SaiRamDash",
  email: "sairam@karmaraj.dev",
  level: 18,
  xp: 1420,
  gold: 1840,
  hp: 92,
  maxHp: 100,
  mp: 80,
  maxMp: 100,
  isSleeping: false,
  streakCount: 14,
  title: "Grand Siddha of Karmaraj",
  avatar: "🧙",
  characterClass: "PALADIN",
  prestigeLevel: 2,
  currentPet: "Solar Phoenix",
  currentMount: "Astral Steed",
  vaultPulls: 18,
  chronoShards: 420,
  stats: {
    strength: 24,
    intellect: 28,
    vitality: 22,
    dexterity: 18,
    charisma: 25,
    sanity: 26,
  },
};

export const DEMO_HABITS = [
  {
    id: "dh-1",
    type: "HABIT" as const,
    title: "1h Focused Deep Work",
    description: "Undistracted spellcraft and quest development without tab switching.",
    category: "INTELLECT",
    difficulty: "HARD",
    up: true,
    down: false,
    value: 18.5,
    counterUp: 24,
    counterDown: 0,
    completedToday: true,
    streak: 14,
    status: "TODO",
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: "dh-2",
    type: "HABIT" as const,
    title: "Vedic Morning Surya Namaskar",
    description: "Greet the dawn sun with 12 fluid cycles of dynamic flow.",
    category: "STRENGTH",
    difficulty: "MEDIUM",
    up: true,
    down: false,
    value: 12.0,
    counterUp: 18,
    counterDown: 0,
    completedToday: true,
    streak: 12,
    status: "TODO",
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: "dh-3",
    type: "HABIT" as const,
    title: "Clean Water Hydration (3L)",
    description: "Maintain fluid vitality throughout cognitive work cycles.",
    category: "VITALITY",
    difficulty: "EASY",
    up: true,
    down: false,
    value: 8.5,
    counterUp: 32,
    counterDown: 0,
    completedToday: true,
    streak: 19,
    status: "TODO",
    createdAt: new Date(Date.now() - 19 * 86400000).toISOString(),
  },
  {
    id: "dh-4",
    type: "HABIT" as const,
    title: "Daily Coding Sprint & PR Review",
    description: "Ship clean, strictly typed, zero-defect TypeScript commits.",
    category: "INTELLECT",
    difficulty: "HARD",
    up: true,
    down: false,
    value: 21.0,
    counterUp: 38,
    counterDown: 0,
    completedToday: false,
    streak: 28,
    status: "TODO",
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  {
    id: "dh-5",
    type: "HABIT" as const,
    title: "Mindless Social Doomscrolling",
    description: "Goblin distraction drains precious vitality and daylight.",
    category: "SANITY",
    difficulty: "MEDIUM",
    up: false,
    down: true,
    value: -4.0,
    counterUp: 0,
    counterDown: 2,
    completedToday: false,
    streak: 0,
    status: "TODO",
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: "dh-6",
    type: "HABIT" as const,
    title: "Junk Fast Food Snacking",
    description: "Heavily processed tavern junk slows down arcane intellect.",
    category: "VITALITY",
    difficulty: "EASY",
    up: false,
    down: true,
    value: -2.5,
    counterUp: 0,
    counterDown: 1,
    completedToday: false,
    streak: 0,
    status: "TODO",
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
];

export const DEMO_DAILIES = [
  {
    id: "dd-1",
    type: "DAILY" as const,
    title: "Morning Sunlight & 15m Pranayama",
    description: "Calibrate circadian hormones and awaken breath awareness.",
    category: "SANITY",
    difficulty: "EASY",
    up: true,
    down: false,
    value: 8.0,
    counterUp: 14,
    counterDown: 0,
    repeatDays: "0,1,2,3,4,5,6",
    completedToday: true,
    streak: 14,
    status: "COMPLETED",
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: "dd-2",
    type: "DAILY" as const,
    title: "Review Project Kanban & Architecture",
    description: "Align daily milestones before executing tactical spells.",
    category: "INTELLECT",
    difficulty: "MEDIUM",
    up: true,
    down: false,
    value: 12.0,
    counterUp: 12,
    counterDown: 0,
    repeatDays: "1,2,3,4,5",
    completedToday: true,
    streak: 12,
    status: "COMPLETED",
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: "dd-3",
    type: "DAILY" as const,
    title: "Evening 30m Dumbbell Hypertrophy",
    description: "Progressive overload on overhead presses and rows.",
    category: "STRENGTH",
    difficulty: "MEDIUM",
    up: true,
    down: false,
    value: 6.0,
    counterUp: 9,
    counterDown: 0,
    repeatDays: "1,2,3,4,5,6",
    completedToday: false,
    streak: 9,
    status: "TODO",
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
  {
    id: "dd-4",
    type: "DAILY" as const,
    title: "Evening Gratitude & Offline Journaling",
    description: "Record 3 breakthroughs and clear mental parchment before sleep.",
    category: "SANITY",
    difficulty: "EASY",
    up: true,
    down: false,
    value: 7.5,
    counterUp: 11,
    counterDown: 0,
    repeatDays: "0,1,2,3,4,5,6",
    completedToday: false,
    streak: 11,
    status: "TODO",
    createdAt: new Date(Date.now() - 11 * 86400000).toISOString(),
  },
];

export const DEMO_TODOS = [
  {
    id: "dt-1",
    type: "TODO" as const,
    title: "Deploy Next.js 16 Production Cluster",
    description: "Configure edge routing, caching headers, and automated smoke test suite.",
    category: "INTELLECT",
    difficulty: "HARD",
    up: true,
    down: false,
    value: 15.0,
    counterUp: 0,
    counterDown: 0,
    completedToday: false,
    streak: 0,
    checklist: JSON.stringify([
      { id: "c1", text: "Audit environment secrets and Postgres connection pool", completed: true },
      { id: "c2", text: "Verify Vitest suite pass rate across 13 test files", completed: true },
      { id: "c3", text: "Deploy Docker container to Kubernetes pod", completed: false },
    ]),
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    status: "TODO",
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "dt-2",
    type: "TODO" as const,
    title: "Publish Open-Source Karmaraj Engine RFC",
    description: "Format behavioral psychology documentation and publish GitHub releases.",
    category: "CHARISMA",
    difficulty: "MEDIUM",
    up: true,
    down: false,
    value: 10.0,
    counterUp: 0,
    counterDown: 0,
    completedToday: false,
    streak: 0,
    checklist: JSON.stringify([
      { id: "c4", text: "Record 4K interactive walkthrough video", completed: true },
      { id: "c5", text: "Draft comprehensive README architectural matrix", completed: true },
      { id: "c6", text: "Share update on LinkedIn engineering community", completed: false },
    ]),
    dueDate: new Date(Date.now() + 86400000 * 4).toISOString(),
    status: "TODO",
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "dt-3",
    type: "TODO" as const,
    title: "Refactor Three.js Voxel Shaders",
    description: "Optimize draw calls and procedural texture memory allocation.",
    category: "DEXTERITY",
    difficulty: "MEDIUM",
    up: true,
    down: false,
    value: 8.0,
    counterUp: 1,
    counterDown: 0,
    completedToday: true,
    streak: 0,
    status: "COMPLETED",
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const DEMO_REWARDS = [
  {
    id: "dr-1",
    type: "REWARD" as const,
    title: "Masala Chai & Garam Samosa at Tavern",
    description: "Authentic ginger cardamom brew and crispy savory snack.",
    category: "SANITY",
    difficulty: "EASY",
    cost: 15,
    up: true,
    down: false,
    value: 0,
    counterUp: 4,
    counterDown: 0,
    completedToday: false,
    streak: 0,
    status: "TODO",
    createdAt: new Date().toISOString(),
  },
  {
    id: "dr-2",
    type: "REWARD" as const,
    title: "2 Hours Uninterrupted Steam Gaming",
    description: "Dungeon crawler session with a completely clean conscience.",
    category: "CHARISMA",
    difficulty: "MEDIUM",
    cost: 40,
    up: true,
    down: false,
    value: 0,
    counterUp: 2,
    counterDown: 0,
    completedToday: false,
    streak: 0,
    status: "TODO",
    createdAt: new Date().toISOString(),
  },
  {
    id: "dr-3",
    type: "REWARD" as const,
    title: "Custom Mechanical Keycap Set",
    description: "High-profile PBT keycaps for maximum tactile thock satisfaction.",
    category: "DEXTERITY",
    difficulty: "HARD",
    cost: 250,
    up: true,
    down: false,
    value: 0,
    counterUp: 0,
    counterDown: 0,
    completedToday: false,
    streak: 0,
    status: "TODO",
    createdAt: new Date().toISOString(),
  },
];

export const DEMO_LOGS = [
  {
    id: "log-1",
    actionType: "CRIT_STRIKE",
    message: "SUDARSHANA CRIT! Completed '1h Focused Deep Work' for +40 XP and +25 Gold.",
    xpChange: 40,
    goldChange: 25,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "log-2",
    actionType: "POMODORO",
    message: "🍅 POMODORO MASTERY! Completed 25m Focus Chamber for +35 XP and +15 Gold.",
    xpChange: 35,
    goldChange: 15,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "log-3",
    actionType: "BOSS_STRIKE",
    message: "Inflicted 140 Raid Damage against Mahishasura of Chaos!",
    xpChange: 15,
    goldChange: 10,
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: "log-4",
    actionType: "LEVEL_UP",
    message: "Ascended to Level 18! Unlocked 'Grand Siddha of Karmaraj' title.",
    xpChange: 0,
    goldChange: 100,
    createdAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
  },
];

export const DEMO_XP_HISTORY = [
  { date: "2026-08-30", displayDate: "Aug 30", xp: 110, tasksCompleted: 5 },
  { date: "2026-08-31", displayDate: "Aug 31", xp: 145, tasksCompleted: 7 },
  { date: "2026-09-01", displayDate: "Sep 01", xp: 130, tasksCompleted: 6 },
  { date: "2026-09-02", displayDate: "Sep 02", xp: 165, tasksCompleted: 8 },
  { date: "2026-09-03", displayDate: "Sep 03", xp: 140, tasksCompleted: 6 },
  { date: "2026-09-04", displayDate: "Sep 04", xp: 190, tasksCompleted: 9 },
  { date: "2026-09-05", displayDate: "Sep 05", xp: 175, tasksCompleted: 8 },
  { date: "2026-09-06", displayDate: "Sep 06", xp: 120, tasksCompleted: 5 },
  { date: "2026-09-07", displayDate: "Sep 07", xp: 155, tasksCompleted: 7 },
  { date: "2026-09-08", displayDate: "Sep 08", xp: 180, tasksCompleted: 8 },
  { date: "2026-09-09", displayDate: "Sep 09", xp: 210, tasksCompleted: 10 },
  { date: "2026-09-10", displayDate: "Sep 10", xp: 160, tasksCompleted: 7 },
  { date: "2026-09-11", displayDate: "Sep 11", xp: 195, tasksCompleted: 9 },
  { date: "2026-09-12", displayDate: "Sep 12", xp: 230, tasksCompleted: 11 },
];
